<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Products_model extends CI_Model
{

    public $table = 'products';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('point', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('name', $q);
	$this->db->or_like('description', $q);
	$this->db->or_like('price', $q);
	$this->db->or_like('stock', $q);
	$this->db->or_like('point', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
public function lihat(){
        $query = $this->db->get($this->table);
        return $query->result();
    }

    public function jumlah(){
        $query = $this->db->get($this->table);
        return $query->num_rows();
    }

    public function lihat_stok(){
        $query = $this->db->get_where($this->table, 'stock > 1');
        return $query->result();
    }

    public function lihat_id($kode_barang){
        $query = $this->db->get_where($this->table, ['id' => $kode_barang]);
        return $query->row();
    }

    public function lihat_nama_barang($name){
        $query = $this->db->select('*');
        $query = $this->db->where(['name' => $name]);
        $query = $this->db->get($this->table);
        return $query->row();
    }

    public function tambah($data){
        return $this->db->insert($this->table, $data);
    }

    public function min_stok($stok, $name){
        $query = $this->db->set('stock', 'stock-' . $stok, false);
        $query = $this->db->where('name', $name);
        $query = $this->db->update($this->table);
        return $query;
    }

    public function ubah($data, $kode_barang){
        $query = $this->db->set($data);
        $query = $this->db->where(['id' => $kode_barang]);
        $query = $this->db->update($this->table);
        return $query;
    }

    public function hapus($kode_barang){
        return $this->db->delete($this->table, ['id' => $kode_barang]);
    }
}

/* End of file Products_model.php */
/* Location: ./application/models/Products_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-11 14:21:59 */
/* http://harviacode.com */